import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Techniques Design Architectures",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" sizes="any" />
        <link
          rel="icon"
          type="image/png"
          sizes="any"
          href="/logo.png"
        ></link>
      </head>
      <body className={inter.className}>
        <div className="App 2xl:text-2xl text-xl lg:font-medium font-normal relative h-full w-full flex flex-col items-end">
          <Navbar />
          {children}
          <div className="w-[90%] flex flex-col justify-center items-center">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
